language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda create -yq -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.conda
  - source activate test-environment
  - pip install -q -r requirements.pip
  - python setup.py install

script:
  - pytest --cov crisprtree

after_success:
  - coveralls